name: Validate JSON

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**.json"

jobs:
  test:
    name: Validate JSON
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
