name: Validate Timeline JSON

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  verify-json-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: /dev/timeline_schema.json
          INPUT_JSONS: /timeline_data.json
